//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduLearn.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public Nullable<int> messageID { get; set; }
        public Nullable<System.DateTime> time_created { get; set; }
        public Nullable<bool> is_read { get; set; }
    
        public virtual MessageTemplate MessageTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
